root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/nomadbank ./cmd/nomadbank"
bin = "./tmp/nomadbank"
args_bin = ["-mode", "dev"]
include_ext = ["go"]
exclude_dir = ["tmp", "frontend", "web", "node_modules"]

[misc]
clean_on_exit = true
